public class InverterStatus
{
    public double Pv1Vol { get; set; }
    public double Pv1Cur { get; set; }
    public double Pv1Power { get; set; }
    public double Pv2Vol { get; set; }
    public double Pv2Cur { get; set; }
    public double Pv2Power { get; set; }
    public double IntTemp { get; set; }
    public double ChargerTemp { get; set; }
    public double BoostTemp { get; set; }
    public double InvTemp { get; set; }
    public double BatteryVol { get; set; }
    public double BatteryCur { get; set; }
    public double BatteryPower { get; set; }
    public double BmsVol { get; set; }
    public double BmsCur { get; set; }
    public double BmsTemp { get; set; }
    public double Soc { get; set; }
    public double Soh { get; set; }
    public int BatteryStatus { get; set; }
    public int CycleTime { get; set; }
    public int AhNum { get; set; }
    public int InvState { get; set; }
    public int BmsState { get; set; }
    public int MeterState { get; set; }
    public int Alarm { get; set; }
    public double GridVol { get; set; }
    public double GridSVol { get; set; }
    public double GridTVol { get; set; }
    public double InvCur { get; set; }
    public double InvSCur { get; set; }
    public double InvTCur { get; set; }
    public double InvPower { get; set; }
    public double InvSPower { get; set; }
    public double InvTPower { get; set; }
    public double GridFre { get; set; }
    public double GridSFre { get; set; }
    public double GridTFre { get; set; }
    public double EpsVol { get; set; }
    public double EpsSVol { get; set; }
    public double EpsTVol { get; set; }
    public double EpsCur { get; set; }
    public double EpsSCur { get; set; }
    public double EpsTCur { get; set; }
    public double EpsPower { get; set; }
    public double EpsSPower { get; set; }
    public double EpsTPower { get; set; }
    public double EpsFre { get; set; }
    public double MeterRPower { get; set; }
    public double MeterSPower { get; set; }
    public double MeterTPower { get; set; }
    public double MeterPower { get; set; }
    public double Meter2RPower { get; set; }
    public double Meter2SPower { get; set; }
    public double Meter2TPower { get; set; }
    public double Meter2Power { get; set; }
    public double Meter3RPower { get; set; }
    public double Meter3SPower { get; set; }
    public double Meter3TPower { get; set; }
    public double Meter3Power { get; set; }
    public double LoadRPower { get; set; }
    public double LoadSPower { get; set; }
    public double LoadTPower { get; set; }
    public double LoadPower { get; set; }

    // Constructor and other methods (if necessary) go here
}
